export type CountryItem = { code: string; dial: string; label: string };

/** Country code list. US (+1) first as default. */
export const COUNTRY_CODES: CountryItem[] = [
  { code: 'US', dial: '+1', label: 'United States' },
  { code: 'CA', dial: '+1', label: 'Canada' },
  { code: 'GB', dial: '+44', label: 'United Kingdom' },
  { code: 'AU', dial: '+61', label: 'Australia' },
  { code: 'DE', dial: '+49', label: 'Germany' },
  { code: 'FR', dial: '+33', label: 'France' },
  { code: 'ES', dial: '+34', label: 'Spain' },
  { code: 'IT', dial: '+39', label: 'Italy' },
  { code: 'NL', dial: '+31', label: 'Netherlands' },
  { code: 'BE', dial: '+32', label: 'Belgium' },
  { code: 'CH', dial: '+41', label: 'Switzerland' },
  { code: 'AT', dial: '+43', label: 'Austria' },
  { code: 'IE', dial: '+353', label: 'Ireland' },
  { code: 'PT', dial: '+351', label: 'Portugal' },
  { code: 'PL', dial: '+48', label: 'Poland' },
  { code: 'SE', dial: '+46', label: 'Sweden' },
  { code: 'NO', dial: '+47', label: 'Norway' },
  { code: 'DK', dial: '+45', label: 'Denmark' },
  { code: 'FI', dial: '+358', label: 'Finland' },
  { code: 'MX', dial: '+52', label: 'Mexico' },
  { code: 'BR', dial: '+55', label: 'Brazil' },
  { code: 'AR', dial: '+54', label: 'Argentina' },
  { code: 'CO', dial: '+57', label: 'Colombia' },
  { code: 'CL', dial: '+56', label: 'Chile' },
  { code: 'IN', dial: '+91', label: 'India' },
  { code: 'JP', dial: '+81', label: 'Japan' },
  { code: 'KR', dial: '+82', label: 'South Korea' },
  { code: 'CN', dial: '+86', label: 'China' },
  { code: 'HK', dial: '+852', label: 'Hong Kong' },
  { code: 'SG', dial: '+65', label: 'Singapore' },
  { code: 'NZ', dial: '+64', label: 'New Zealand' },
  { code: 'ZA', dial: '+27', label: 'South Africa' },
  { code: 'NG', dial: '+234', label: 'Nigeria' },
  { code: 'EG', dial: '+20', label: 'Egypt' },
  { code: 'IL', dial: '+972', label: 'Israel' },
  { code: 'AE', dial: '+971', label: 'UAE' },
  { code: 'SA', dial: '+966', label: 'Saudi Arabia' },
  { code: 'TR', dial: '+90', label: 'Turkey' },
  { code: 'RU', dial: '+7', label: 'Russia' },
  { code: 'UA', dial: '+380', label: 'Ukraine' },
  { code: 'PH', dial: '+63', label: 'Philippines' },
  { code: 'TH', dial: '+66', label: 'Thailand' },
  { code: 'MY', dial: '+60', label: 'Malaysia' },
  { code: 'ID', dial: '+62', label: 'Indonesia' },
  { code: 'VN', dial: '+84', label: 'Vietnam' },
];

export const DEFAULT_COUNTRY = COUNTRY_CODES[0]; // US
